[package]
name = "einsteindb"
version = "0.1.0"
authors = ["YosiSF"]


[dependencies]
#our dependencies are in whtcorpsinc/einsteindb-prod.git 
einsteindb-prod = {git = "https://github.com/whtcorpsinc/einsteindb-prod.git" }

#the rest of our dependencies are in YosiSF/EinsteinDB itself, which we will need to build and run inside YosiSF/EinsteinDB itself
serde_json = "1.0.78"   #this is a dependency that we will need to build ourselves and use inside our project
serde_derive = "1.0.136" #this is a dependency that we will need to build ourselves and use inside our project
log4rs = "1.0.0"      #this is a dependency that we will need to build ourselves and use inside our project
#log4rs_syslog4rs= { version="*", features=["syslog"] }   