[package]
name = "core_traits"
version = "0.0.1"
workspace = "../.."

[lib]
name = "core_traits"
local_path = "lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
enum-set = "0.0.8"
lazy_static = "1.4.0"
indexmap = "1"
ordered-float = { version = "2.10.0", features = ["serde"] }
uuid = { version = "0.8.2", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"

[dependencies.edn]
local_path = "../edn"
features = ["serde_support"]
