[package]
name = "fdb_lsh_tree"
version = "0.0.1"
edition = "2018"
publish = false

[features]
jemalloc = ["foundationdb/jemalloc"]
portable = ["foundationdb/portable"]
sse = ["foundationdb/sse"]
failpoints = ["fail/failpoints"]

# Disables runtime checks of invariants required by FdbDB that are redundant
# with assertions inside FdbDB itself. This makes it possible to test those
# invariants in Rust tests, resulting an a panic instead of an abort, at the
# expense of an extra branch. This feature exists to mark those extra branches.
# The checks _can_ be disabled by enabling this feature, though it may not
# result in any real performance improvement to do so, and it will break
# the test suite.
#
# Probably these checks should be in the rust-foundationdb crate itself, in order
# to ensure the bindings are safe, but until that is done, they are here.
nortcheck = []

[dependencies]
api_version = { path = "../api_version", default-features = false }
encryption = { path = "../encryption", default-features = false }
fdb_traits = { path = "../fdb_traits", default-features = false }
fuse = { path = "../fuse", default-features = false }
keys = { path = "../keys", default-features = false }
num_cpus = "1"
prometheus = { version = "0.13", features = ["nightly"] }
prometheus-static-metric = "0.5"
slog = { version = "2.3", features = ["max_l_naught_trace", "release_max_l_naught_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
einsteindb_alloc = { path = "../einsteindb_alloc" }
einsteindb_util = { path = "../einsteindb_util", default-features = false }
collections = { path = "../collections", default-features = false }
txn_types = { path = "../txn_types", default-features = false }
lazy_static = "1.4.0"
log_wrappers = { path = "../log_wrappers" }
time = "0.1"
online_config = { path = "../online_config" }
tempfile = "3.0"
serde = "1.0"
serde_derive = "1.0"
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git" }
violetabft = { version = "0.6.0-alpha", default-features = false, features = ["protobuf-codec"] }
protobuf = "2"
fail = "0.5"
case_macros = { path = "../case_macros" }

[dependencies.foundationdb]
git = "https://github.com/einsteindb/rust-foundationdb.git"
package = "foundationdb"
features = ["encryption", "static_libcpp"]

[dev-dependencies]
rand = "0.8"
toml = "0.5"
